### ISSUE TITLE
Add a jokes command?

### ISSUE THREAD

**Issue by Myushii** [zfbx/Yuno#2]
I think your Yuno bot should be able to tell jokes when ever commanded! :3

**Comment by zfbx** [comment]
So a .. simple `.joke`. what about `.knockknock` (`.knock` for short?) or `.yourmomma`? xD

**Comment by Myushii** [comment]
I think if you add .yourmomma jokes, you should just make commands such as ".insult." or ".compliment" and have a separate  ".joke" that's neither compliments or insults. Just funny lame jokes or pick up lines, maybe ?..

**Comment by zfbx** [comment]
perfect, will add those when I have a free minute xD

**Comment by zfbx** [comment]
Joke categories should be a thing too like .joke anime or .joke dad

**Comment by zfbx** [comment]
Added jokes command in this commit a8ac39930d419a9fa9d463ac759db1e3aca00506 

Jokes currently have about ~190 at the moment but can be expanded.
