### ISSUE TITLE
Game Profiles 

### ISSUE THREAD

**Issue by Kiracidic** [zfbx/Yuno#3]
I've seen some bots show game profiles such as osu! and Overwatch. Like it shows your level, how long you've played, when you joined, the such. ARE YOU UP TO THE TEST? I'm not sure exactly all the games you can do it with but I've seen Paladins, Overwatch, and osu! be able to do it. Plus I think Kayree would like the Paladins profile command. If you need to me to I can try to find a link to the bot to give you an example of what it looks like if you have no clue what i'm talking about.

**Comment by zfbx** [comment]
Seems fair enough, I know what you're talking about, Nadeko yuno has it built in, I'll see what I can do.
